//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("testdb1Model", "FK_properties_images", "images", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LLMS.image), "properties", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LLMS.property), true)]
[assembly: EdmRelationshipAttribute("testdb1Model", "FK_tenants_images", "images", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LLMS.image), "tenants", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LLMS.tenant), true)]
[assembly: EdmRelationshipAttribute("testdb1Model", "FK_leases_properties", "properties", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LLMS.property), "leases", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LLMS.leas), true)]
[assembly: EdmRelationshipAttribute("testdb1Model", "FK_leases_tenants", "tenants", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LLMS.tenant), "leases", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LLMS.leas), true)]

#endregion

namespace LLMS
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class testdb1Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new testdb1Entities object using the connection string found in the 'testdb1Entities' section of the application configuration file.
        /// </summary>
        public testdb1Entities() : base("name=testdb1Entities", "testdb1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new testdb1Entities object.
        /// </summary>
        public testdb1Entities(string connectionString) : base(connectionString, "testdb1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new testdb1Entities object.
        /// </summary>
        public testdb1Entities(EntityConnection connection) : base(connection, "testdb1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<image> images
        {
            get
            {
                if ((_images == null))
                {
                    _images = base.CreateObjectSet<image>("images");
                }
                return _images;
            }
        }
        private ObjectSet<image> _images;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<leas> leases
        {
            get
            {
                if ((_leases == null))
                {
                    _leases = base.CreateObjectSet<leas>("leases");
                }
                return _leases;
            }
        }
        private ObjectSet<leas> _leases;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<property> properties
        {
            get
            {
                if ((_properties == null))
                {
                    _properties = base.CreateObjectSet<property>("properties");
                }
                return _properties;
            }
        }
        private ObjectSet<property> _properties;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tenant> tenants
        {
            get
            {
                if ((_tenants == null))
                {
                    _tenants = base.CreateObjectSet<tenant>("tenants");
                }
                return _tenants;
            }
        }
        private ObjectSet<tenant> _tenants;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the images EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToimages(image image)
        {
            base.AddObject("images", image);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the leases EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToleases(leas leas)
        {
            base.AddObject("leases", leas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the properties EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproperties(property property)
        {
            base.AddObject("properties", property);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tenants EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotenants(tenant tenant)
        {
            base.AddObject("tenants", tenant);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testdb1Model", Name="image")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class image : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new image object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="image_url">Initial value of the image_url property.</param>
        /// <param name="uploaded_at">Initial value of the uploaded_at property.</param>
        public static image Createimage(global::System.Int32 id, global::System.String image_url, global::System.DateTime uploaded_at)
        {
            image image = new image();
            image.id = id;
            image.image_url = image_url;
            image.uploaded_at = uploaded_at;
            return image;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String image_url
        {
            get
            {
                return _image_url;
            }
            set
            {
                Onimage_urlChanging(value);
                ReportPropertyChanging("image_url");
                _image_url = StructuralObject.SetValidValue(value, false, "image_url");
                ReportPropertyChanged("image_url");
                Onimage_urlChanged();
            }
        }
        private global::System.String _image_url;
        partial void Onimage_urlChanging(global::System.String value);
        partial void Onimage_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime uploaded_at
        {
            get
            {
                return _uploaded_at;
            }
            set
            {
                Onuploaded_atChanging(value);
                ReportPropertyChanging("uploaded_at");
                _uploaded_at = StructuralObject.SetValidValue(value, "uploaded_at");
                ReportPropertyChanged("uploaded_at");
                Onuploaded_atChanged();
            }
        }
        private global::System.DateTime _uploaded_at;
        partial void Onuploaded_atChanging(global::System.DateTime value);
        partial void Onuploaded_atChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testdb1Model", "FK_properties_images", "properties")]
        public EntityCollection<property> properties
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<property>("testdb1Model.FK_properties_images", "properties");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<property>("testdb1Model.FK_properties_images", "properties", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testdb1Model", "FK_tenants_images", "tenants")]
        public EntityCollection<tenant> tenants
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tenant>("testdb1Model.FK_tenants_images", "tenants");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tenant>("testdb1Model.FK_tenants_images", "tenants", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testdb1Model", Name="leas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class leas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new leas object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="property_id">Initial value of the property_id property.</param>
        /// <param name="tenant_id">Initial value of the tenant_id property.</param>
        /// <param name="start_date">Initial value of the start_date property.</param>
        /// <param name="end_date">Initial value of the end_date property.</param>
        /// <param name="rent_amount">Initial value of the rent_amount property.</param>
        /// <param name="created_at">Initial value of the created_at property.</param>
        /// <param name="payment_due_day">Initial value of the payment_due_day property.</param>
        public static leas Createleas(global::System.Int32 id, global::System.Int32 property_id, global::System.Int32 tenant_id, global::System.DateTime start_date, global::System.DateTime end_date, global::System.Decimal rent_amount, global::System.DateTime created_at, global::System.Int32 payment_due_day)
        {
            leas leas = new leas();
            leas.id = id;
            leas.property_id = property_id;
            leas.tenant_id = tenant_id;
            leas.start_date = start_date;
            leas.end_date = end_date;
            leas.rent_amount = rent_amount;
            leas.created_at = created_at;
            leas.payment_due_day = payment_due_day;
            return leas;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 property_id
        {
            get
            {
                return _property_id;
            }
            set
            {
                Onproperty_idChanging(value);
                ReportPropertyChanging("property_id");
                _property_id = StructuralObject.SetValidValue(value, "property_id");
                ReportPropertyChanged("property_id");
                Onproperty_idChanged();
            }
        }
        private global::System.Int32 _property_id;
        partial void Onproperty_idChanging(global::System.Int32 value);
        partial void Onproperty_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tenant_id
        {
            get
            {
                return _tenant_id;
            }
            set
            {
                Ontenant_idChanging(value);
                ReportPropertyChanging("tenant_id");
                _tenant_id = StructuralObject.SetValidValue(value, "tenant_id");
                ReportPropertyChanged("tenant_id");
                Ontenant_idChanged();
            }
        }
        private global::System.Int32 _tenant_id;
        partial void Ontenant_idChanging(global::System.Int32 value);
        partial void Ontenant_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime start_date
        {
            get
            {
                return _start_date;
            }
            set
            {
                Onstart_dateChanging(value);
                ReportPropertyChanging("start_date");
                _start_date = StructuralObject.SetValidValue(value, "start_date");
                ReportPropertyChanged("start_date");
                Onstart_dateChanged();
            }
        }
        private global::System.DateTime _start_date;
        partial void Onstart_dateChanging(global::System.DateTime value);
        partial void Onstart_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime end_date
        {
            get
            {
                return _end_date;
            }
            set
            {
                Onend_dateChanging(value);
                ReportPropertyChanging("end_date");
                _end_date = StructuralObject.SetValidValue(value, "end_date");
                ReportPropertyChanged("end_date");
                Onend_dateChanged();
            }
        }
        private global::System.DateTime _end_date;
        partial void Onend_dateChanging(global::System.DateTime value);
        partial void Onend_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal rent_amount
        {
            get
            {
                return _rent_amount;
            }
            set
            {
                Onrent_amountChanging(value);
                ReportPropertyChanging("rent_amount");
                _rent_amount = StructuralObject.SetValidValue(value, "rent_amount");
                ReportPropertyChanged("rent_amount");
                Onrent_amountChanged();
            }
        }
        private global::System.Decimal _rent_amount;
        partial void Onrent_amountChanging(global::System.Decimal value);
        partial void Onrent_amountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created_at
        {
            get
            {
                return _created_at;
            }
            set
            {
                Oncreated_atChanging(value);
                ReportPropertyChanging("created_at");
                _created_at = StructuralObject.SetValidValue(value, "created_at");
                ReportPropertyChanged("created_at");
                Oncreated_atChanged();
            }
        }
        private global::System.DateTime _created_at;
        partial void Oncreated_atChanging(global::System.DateTime value);
        partial void Oncreated_atChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> updated_at
        {
            get
            {
                return _updated_at;
            }
            set
            {
                Onupdated_atChanging(value);
                ReportPropertyChanging("updated_at");
                _updated_at = StructuralObject.SetValidValue(value, "updated_at");
                ReportPropertyChanged("updated_at");
                Onupdated_atChanged();
            }
        }
        private Nullable<global::System.DateTime> _updated_at;
        partial void Onupdated_atChanging(Nullable<global::System.DateTime> value);
        partial void Onupdated_atChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lease_clauses
        {
            get
            {
                return _lease_clauses;
            }
            set
            {
                Onlease_clausesChanging(value);
                ReportPropertyChanging("lease_clauses");
                _lease_clauses = StructuralObject.SetValidValue(value, true, "lease_clauses");
                ReportPropertyChanged("lease_clauses");
                Onlease_clausesChanged();
            }
        }
        private global::System.String _lease_clauses;
        partial void Onlease_clausesChanging(global::System.String value);
        partial void Onlease_clausesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 payment_due_day
        {
            get
            {
                return _payment_due_day;
            }
            set
            {
                Onpayment_due_dayChanging(value);
                ReportPropertyChanging("payment_due_day");
                _payment_due_day = StructuralObject.SetValidValue(value, "payment_due_day");
                ReportPropertyChanged("payment_due_day");
                Onpayment_due_dayChanged();
            }
        }
        private global::System.Int32 _payment_due_day;
        partial void Onpayment_due_dayChanging(global::System.Int32 value);
        partial void Onpayment_due_dayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String utility_by_owner
        {
            get
            {
                return _utility_by_owner;
            }
            set
            {
                Onutility_by_ownerChanging(value);
                ReportPropertyChanging("utility_by_owner");
                _utility_by_owner = StructuralObject.SetValidValue(value, true, "utility_by_owner");
                ReportPropertyChanged("utility_by_owner");
                Onutility_by_ownerChanged();
            }
        }
        private global::System.String _utility_by_owner;
        partial void Onutility_by_ownerChanging(global::System.String value);
        partial void Onutility_by_ownerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String utility_by_tenant
        {
            get
            {
                return _utility_by_tenant;
            }
            set
            {
                Onutility_by_tenantChanging(value);
                ReportPropertyChanging("utility_by_tenant");
                _utility_by_tenant = StructuralObject.SetValidValue(value, true, "utility_by_tenant");
                ReportPropertyChanged("utility_by_tenant");
                Onutility_by_tenantChanged();
            }
        }
        private global::System.String _utility_by_tenant;
        partial void Onutility_by_tenantChanging(global::System.String value);
        partial void Onutility_by_tenantChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String renewal_term
        {
            get
            {
                return _renewal_term;
            }
            set
            {
                Onrenewal_termChanging(value);
                ReportPropertyChanging("renewal_term");
                _renewal_term = StructuralObject.SetValidValue(value, true, "renewal_term");
                ReportPropertyChanged("renewal_term");
                Onrenewal_termChanged();
            }
        }
        private global::System.String _renewal_term;
        partial void Onrenewal_termChanging(global::System.String value);
        partial void Onrenewal_termChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String early_terminate_con
        {
            get
            {
                return _early_terminate_con;
            }
            set
            {
                Onearly_terminate_conChanging(value);
                ReportPropertyChanging("early_terminate_con");
                _early_terminate_con = StructuralObject.SetValidValue(value, true, "early_terminate_con");
                ReportPropertyChanged("early_terminate_con");
                Onearly_terminate_conChanged();
            }
        }
        private global::System.String _early_terminate_con;
        partial void Onearly_terminate_conChanging(global::System.String value);
        partial void Onearly_terminate_conChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testdb1Model", "FK_leases_properties", "properties")]
        public property property
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<property>("testdb1Model.FK_leases_properties", "properties").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<property>("testdb1Model.FK_leases_properties", "properties").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<property> propertyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<property>("testdb1Model.FK_leases_properties", "properties");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<property>("testdb1Model.FK_leases_properties", "properties", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testdb1Model", "FK_leases_tenants", "tenants")]
        public tenant tenant
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tenant>("testdb1Model.FK_leases_tenants", "tenants").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tenant>("testdb1Model.FK_leases_tenants", "tenants").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tenant> tenantReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tenant>("testdb1Model.FK_leases_tenants", "tenants");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tenant>("testdb1Model.FK_leases_tenants", "tenants", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testdb1Model", Name="property")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class property : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new property object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="address">Initial value of the address property.</param>
        /// <param name="number_of_units">Initial value of the number_of_units property.</param>
        /// <param name="created_at">Initial value of the created_at property.</param>
        /// <param name="property_type">Initial value of the property_type property.</param>
        /// <param name="size_in_sq_ft">Initial value of the size_in_sq_ft property.</param>
        /// <param name="year_built">Initial value of the year_built property.</param>
        /// <param name="rental_price">Initial value of the rental_price property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="lease_terms">Initial value of the lease_terms property.</param>
        /// <param name="image_id">Initial value of the image_id property.</param>
        public static property Createproperty(global::System.Int32 id, global::System.String address, global::System.Int32 number_of_units, global::System.DateTime created_at, global::System.String property_type, global::System.Int32 size_in_sq_ft, global::System.DateTime year_built, global::System.Decimal rental_price, global::System.Int32 status, global::System.String lease_terms, global::System.Int32 image_id)
        {
            property property = new property();
            property.id = id;
            property.address = address;
            property.number_of_units = number_of_units;
            property.created_at = created_at;
            property.property_type = property_type;
            property.size_in_sq_ft = size_in_sq_ft;
            property.year_built = year_built;
            property.rental_price = rental_price;
            property.status = status;
            property.lease_terms = lease_terms;
            property.image_id = image_id;
            return property;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, false, "address");
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 number_of_units
        {
            get
            {
                return _number_of_units;
            }
            set
            {
                Onnumber_of_unitsChanging(value);
                ReportPropertyChanging("number_of_units");
                _number_of_units = StructuralObject.SetValidValue(value, "number_of_units");
                ReportPropertyChanged("number_of_units");
                Onnumber_of_unitsChanged();
            }
        }
        private global::System.Int32 _number_of_units;
        partial void Onnumber_of_unitsChanging(global::System.Int32 value);
        partial void Onnumber_of_unitsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created_at
        {
            get
            {
                return _created_at;
            }
            set
            {
                Oncreated_atChanging(value);
                ReportPropertyChanging("created_at");
                _created_at = StructuralObject.SetValidValue(value, "created_at");
                ReportPropertyChanged("created_at");
                Oncreated_atChanged();
            }
        }
        private global::System.DateTime _created_at;
        partial void Oncreated_atChanging(global::System.DateTime value);
        partial void Oncreated_atChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> updated_at
        {
            get
            {
                return _updated_at;
            }
            set
            {
                Onupdated_atChanging(value);
                ReportPropertyChanging("updated_at");
                _updated_at = StructuralObject.SetValidValue(value, "updated_at");
                ReportPropertyChanged("updated_at");
                Onupdated_atChanged();
            }
        }
        private Nullable<global::System.DateTime> _updated_at;
        partial void Onupdated_atChanging(Nullable<global::System.DateTime> value);
        partial void Onupdated_atChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String property_type
        {
            get
            {
                return _property_type;
            }
            set
            {
                Onproperty_typeChanging(value);
                ReportPropertyChanging("property_type");
                _property_type = StructuralObject.SetValidValue(value, false, "property_type");
                ReportPropertyChanged("property_type");
                Onproperty_typeChanged();
            }
        }
        private global::System.String _property_type;
        partial void Onproperty_typeChanging(global::System.String value);
        partial void Onproperty_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 size_in_sq_ft
        {
            get
            {
                return _size_in_sq_ft;
            }
            set
            {
                Onsize_in_sq_ftChanging(value);
                ReportPropertyChanging("size_in_sq_ft");
                _size_in_sq_ft = StructuralObject.SetValidValue(value, "size_in_sq_ft");
                ReportPropertyChanged("size_in_sq_ft");
                Onsize_in_sq_ftChanged();
            }
        }
        private global::System.Int32 _size_in_sq_ft;
        partial void Onsize_in_sq_ftChanging(global::System.Int32 value);
        partial void Onsize_in_sq_ftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime year_built
        {
            get
            {
                return _year_built;
            }
            set
            {
                Onyear_builtChanging(value);
                ReportPropertyChanging("year_built");
                _year_built = StructuralObject.SetValidValue(value, "year_built");
                ReportPropertyChanged("year_built");
                Onyear_builtChanged();
            }
        }
        private global::System.DateTime _year_built;
        partial void Onyear_builtChanging(global::System.DateTime value);
        partial void Onyear_builtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal rental_price
        {
            get
            {
                return _rental_price;
            }
            set
            {
                Onrental_priceChanging(value);
                ReportPropertyChanging("rental_price");
                _rental_price = StructuralObject.SetValidValue(value, "rental_price");
                ReportPropertyChanged("rental_price");
                Onrental_priceChanged();
            }
        }
        private global::System.Decimal _rental_price;
        partial void Onrental_priceChanging(global::System.Decimal value);
        partial void Onrental_priceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String amenities
        {
            get
            {
                return _amenities;
            }
            set
            {
                OnamenitiesChanging(value);
                ReportPropertyChanging("amenities");
                _amenities = StructuralObject.SetValidValue(value, true, "amenities");
                ReportPropertyChanged("amenities");
                OnamenitiesChanged();
            }
        }
        private global::System.String _amenities;
        partial void OnamenitiesChanging(global::System.String value);
        partial void OnamenitiesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, "status");
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Int32 _status;
        partial void OnstatusChanging(global::System.Int32 value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lease_terms
        {
            get
            {
                return _lease_terms;
            }
            set
            {
                Onlease_termsChanging(value);
                ReportPropertyChanging("lease_terms");
                _lease_terms = StructuralObject.SetValidValue(value, false, "lease_terms");
                ReportPropertyChanged("lease_terms");
                Onlease_termsChanged();
            }
        }
        private global::System.String _lease_terms;
        partial void Onlease_termsChanging(global::System.String value);
        partial void Onlease_termsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 image_id
        {
            get
            {
                return _image_id;
            }
            set
            {
                Onimage_idChanging(value);
                ReportPropertyChanging("image_id");
                _image_id = StructuralObject.SetValidValue(value, "image_id");
                ReportPropertyChanged("image_id");
                Onimage_idChanged();
            }
        }
        private global::System.Int32 _image_id;
        partial void Onimage_idChanging(global::System.Int32 value);
        partial void Onimage_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true, "description");
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testdb1Model", "FK_properties_images", "images")]
        public image image
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<image>("testdb1Model.FK_properties_images", "images").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<image>("testdb1Model.FK_properties_images", "images").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<image> imageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<image>("testdb1Model.FK_properties_images", "images");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<image>("testdb1Model.FK_properties_images", "images", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testdb1Model", "FK_leases_properties", "leases")]
        public EntityCollection<leas> leases
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<leas>("testdb1Model.FK_leases_properties", "leases");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<leas>("testdb1Model.FK_leases_properties", "leases", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testdb1Model", Name="tenant")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tenant : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tenant object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="first_name">Initial value of the first_name property.</param>
        public static tenant Createtenant(global::System.Int32 id, global::System.String email, global::System.String first_name)
        {
            tenant tenant = new tenant();
            tenant.id = id;
            tenant.email = email;
            tenant.first_name = first_name;
            return tenant;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> updated_at
        {
            get
            {
                return _updated_at;
            }
            set
            {
                Onupdated_atChanging(value);
                ReportPropertyChanging("updated_at");
                _updated_at = StructuralObject.SetValidValue(value, "updated_at");
                ReportPropertyChanged("updated_at");
                Onupdated_atChanged();
            }
        }
        private Nullable<global::System.DateTime> _updated_at;
        partial void Onupdated_atChanging(Nullable<global::System.DateTime> value);
        partial void Onupdated_atChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String first_name
        {
            get
            {
                return _first_name;
            }
            set
            {
                Onfirst_nameChanging(value);
                ReportPropertyChanging("first_name");
                _first_name = StructuralObject.SetValidValue(value, false, "first_name");
                ReportPropertyChanged("first_name");
                Onfirst_nameChanged();
            }
        }
        private global::System.String _first_name;
        partial void Onfirst_nameChanging(global::System.String value);
        partial void Onfirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String last_name
        {
            get
            {
                return _last_name;
            }
            set
            {
                Onlast_nameChanging(value);
                ReportPropertyChanging("last_name");
                _last_name = StructuralObject.SetValidValue(value, true, "last_name");
                ReportPropertyChanged("last_name");
                Onlast_nameChanged();
            }
        }
        private global::System.String _last_name;
        partial void Onlast_nameChanging(global::System.String value);
        partial void Onlast_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String street_number
        {
            get
            {
                return _street_number;
            }
            set
            {
                Onstreet_numberChanging(value);
                ReportPropertyChanging("street_number");
                _street_number = StructuralObject.SetValidValue(value, true, "street_number");
                ReportPropertyChanged("street_number");
                Onstreet_numberChanged();
            }
        }
        private global::System.String _street_number;
        partial void Onstreet_numberChanging(global::System.String value);
        partial void Onstreet_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String street_name
        {
            get
            {
                return _street_name;
            }
            set
            {
                Onstreet_nameChanging(value);
                ReportPropertyChanging("street_name");
                _street_name = StructuralObject.SetValidValue(value, true, "street_name");
                ReportPropertyChanged("street_name");
                Onstreet_nameChanged();
            }
        }
        private global::System.String _street_name;
        partial void Onstreet_nameChanging(global::System.String value);
        partial void Onstreet_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city_name
        {
            get
            {
                return _city_name;
            }
            set
            {
                Oncity_nameChanging(value);
                ReportPropertyChanging("city_name");
                _city_name = StructuralObject.SetValidValue(value, true, "city_name");
                ReportPropertyChanged("city_name");
                Oncity_nameChanged();
            }
        }
        private global::System.String _city_name;
        partial void Oncity_nameChanging(global::System.String value);
        partial void Oncity_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String postcode
        {
            get
            {
                return _postcode;
            }
            set
            {
                OnpostcodeChanging(value);
                ReportPropertyChanging("postcode");
                _postcode = StructuralObject.SetValidValue(value, true, "postcode");
                ReportPropertyChanged("postcode");
                OnpostcodeChanged();
            }
        }
        private global::System.String _postcode;
        partial void OnpostcodeChanging(global::System.String value);
        partial void OnpostcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String province
        {
            get
            {
                return _province;
            }
            set
            {
                OnprovinceChanging(value);
                ReportPropertyChanging("province");
                _province = StructuralObject.SetValidValue(value, true, "province");
                ReportPropertyChanged("province");
                OnprovinceChanged();
            }
        }
        private global::System.String _province;
        partial void OnprovinceChanging(global::System.String value);
        partial void OnprovinceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone_number
        {
            get
            {
                return _phone_number;
            }
            set
            {
                Onphone_numberChanging(value);
                ReportPropertyChanging("phone_number");
                _phone_number = StructuralObject.SetValidValue(value, true, "phone_number");
                ReportPropertyChanged("phone_number");
                Onphone_numberChanged();
            }
        }
        private global::System.String _phone_number;
        partial void Onphone_numberChanging(global::System.String value);
        partial void Onphone_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> profile_image_id
        {
            get
            {
                return _profile_image_id;
            }
            set
            {
                Onprofile_image_idChanging(value);
                ReportPropertyChanging("profile_image_id");
                _profile_image_id = StructuralObject.SetValidValue(value, "profile_image_id");
                ReportPropertyChanged("profile_image_id");
                Onprofile_image_idChanged();
            }
        }
        private Nullable<global::System.Int32> _profile_image_id;
        partial void Onprofile_image_idChanging(Nullable<global::System.Int32> value);
        partial void Onprofile_image_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_of_birth
        {
            get
            {
                return _date_of_birth;
            }
            set
            {
                Ondate_of_birthChanging(value);
                ReportPropertyChanging("date_of_birth");
                _date_of_birth = StructuralObject.SetValidValue(value, "date_of_birth");
                ReportPropertyChanged("date_of_birth");
                Ondate_of_birthChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_of_birth;
        partial void Ondate_of_birthChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_of_birthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emergency_contact_name
        {
            get
            {
                return _emergency_contact_name;
            }
            set
            {
                Onemergency_contact_nameChanging(value);
                ReportPropertyChanging("emergency_contact_name");
                _emergency_contact_name = StructuralObject.SetValidValue(value, true, "emergency_contact_name");
                ReportPropertyChanged("emergency_contact_name");
                Onemergency_contact_nameChanged();
            }
        }
        private global::System.String _emergency_contact_name;
        partial void Onemergency_contact_nameChanging(global::System.String value);
        partial void Onemergency_contact_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emergency_contact_number
        {
            get
            {
                return _emergency_contact_number;
            }
            set
            {
                Onemergency_contact_numberChanging(value);
                ReportPropertyChanging("emergency_contact_number");
                _emergency_contact_number = StructuralObject.SetValidValue(value, true, "emergency_contact_number");
                ReportPropertyChanged("emergency_contact_number");
                Onemergency_contact_numberChanged();
            }
        }
        private global::System.String _emergency_contact_number;
        partial void Onemergency_contact_numberChanging(global::System.String value);
        partial void Onemergency_contact_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String national_id
        {
            get
            {
                return _national_id;
            }
            set
            {
                Onnational_idChanging(value);
                ReportPropertyChanging("national_id");
                _national_id = StructuralObject.SetValidValue(value, true, "national_id");
                ReportPropertyChanged("national_id");
                Onnational_idChanged();
            }
        }
        private global::System.String _national_id;
        partial void Onnational_idChanging(global::System.String value);
        partial void Onnational_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String employer_info
        {
            get
            {
                return _employer_info;
            }
            set
            {
                Onemployer_infoChanging(value);
                ReportPropertyChanging("employer_info");
                _employer_info = StructuralObject.SetValidValue(value, true, "employer_info");
                ReportPropertyChanged("employer_info");
                Onemployer_infoChanged();
            }
        }
        private global::System.String _employer_info;
        partial void Onemployer_infoChanging(global::System.String value);
        partial void Onemployer_infoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bank_info
        {
            get
            {
                return _bank_info;
            }
            set
            {
                Onbank_infoChanging(value);
                ReportPropertyChanging("bank_info");
                _bank_info = StructuralObject.SetValidValue(value, true, "bank_info");
                ReportPropertyChanged("bank_info");
                Onbank_infoChanged();
            }
        }
        private global::System.String _bank_info;
        partial void Onbank_infoChanging(global::System.String value);
        partial void Onbank_infoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reference_url
        {
            get
            {
                return _reference_url;
            }
            set
            {
                Onreference_urlChanging(value);
                ReportPropertyChanging("reference_url");
                _reference_url = StructuralObject.SetValidValue(value, true, "reference_url");
                ReportPropertyChanged("reference_url");
                Onreference_urlChanged();
            }
        }
        private global::System.String _reference_url;
        partial void Onreference_urlChanging(global::System.String value);
        partial void Onreference_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_verified
        {
            get
            {
                return _is_verified;
            }
            set
            {
                Onis_verifiedChanging(value);
                ReportPropertyChanging("is_verified");
                _is_verified = StructuralObject.SetValidValue(value, "is_verified");
                ReportPropertyChanged("is_verified");
                Onis_verifiedChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_verified;
        partial void Onis_verifiedChanging(Nullable<global::System.Boolean> value);
        partial void Onis_verifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> created_at
        {
            get
            {
                return _created_at;
            }
            set
            {
                Oncreated_atChanging(value);
                ReportPropertyChanging("created_at");
                _created_at = StructuralObject.SetValidValue(value, "created_at");
                ReportPropertyChanged("created_at");
                Oncreated_atChanged();
            }
        }
        private Nullable<global::System.DateTime> _created_at;
        partial void Oncreated_atChanging(Nullable<global::System.DateTime> value);
        partial void Oncreated_atChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testdb1Model", "FK_tenants_images", "images")]
        public image image
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<image>("testdb1Model.FK_tenants_images", "images").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<image>("testdb1Model.FK_tenants_images", "images").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<image> imageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<image>("testdb1Model.FK_tenants_images", "images");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<image>("testdb1Model.FK_tenants_images", "images", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testdb1Model", "FK_leases_tenants", "leases")]
        public EntityCollection<leas> leases
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<leas>("testdb1Model.FK_leases_tenants", "leases");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<leas>("testdb1Model.FK_leases_tenants", "leases", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
